// Generated by scripts/gen-validators.mjs from
// protocol/schemas/envelope.schema.json — do not edit. Regenerate with
// `npm run gen:validators` whenever the schema changes. No runtime eval:
// MV3 CSP forbids it.
import type { ErrorObject } from "ajv";

type ValidateFn = ((data: unknown, ctx?: object) => boolean) & {
  errors?: ErrorObject[] | null;
};

export declare const validateMessage: ValidateFn;
export declare const validatePlayerState: ValidateFn;
export declare const validateSearchSongsResult: ValidateFn;
export declare const validateTargetsListResult: ValidateFn;
